### ISSUE TITLE
Retropie install - On launch Segmentation Fault > Retroarch Main Menu

### ISSUE THREAD

**Issue by Rarefy-Dev** [alexis-puska/lr-multi-bomberman#4]
Hello,
After following your steps with:
Emulationstation V2.6.5RP
 Linux 4.9.35-v7+ armv7l GNU/Linux
:~/RetroPie-Setup $ git show
commit 9b4fc28c9c05ecedb3899f463ff3c7496160f6ac
Merge: cd3869a a3856ff
Author: Conn O'Griofa <connogriofa@gmail.com>
Date:   Fri Nov 24 23:14:04 2017 +0000
Merge pull request #2213 from psyke83/attractmode_newvendorlibs

I get sent to the Retroarch main menu.  Do you have any suggestions on where I went wrong?

*EDIT*
Messing around I did the items above the directions:
sudo nano /etc/dphys-swapfile The default value in Raspbian is:
CONF_SWAPSIZE=100
change to

CONF_SWAPSIZE=200
edit the file : Makefile.libretro
uncomment the line : #platform = rpi
add 3 for the raspberry pi 3
Rebooted.

Now I get 
Init sprite system
init font text system
 then it hangs
If i hit Ctrl+C i go back to the menu.

Rarefy

**Comment by alexis-puska** [comment]
It's a bug in the SDL2_mixer, what is the distribution that you use for you arm device ?

**Comment by Rarefy-Dev** [comment]
Oops, that’s important.  Raspbian

**Comment by alexis-puska** [comment]
with retropie, recallbox ? this bug is since que version 3.9 of retropie. I don't know why the new version of Jessie (raspbian) the SDL2_mixer is stuck on the initialisation. i need to found time to fix it
If you want to test this bomberman, you can use with retropie 3.8

**Comment by Rarefy-Dev** [comment]
I hadn't heard of recallbox.  Will check that out.  Im setting up a bunch of game servers for my 9 year old's birthday sleepover this weekend.  Looking for games that all 6 can be in at same time.  Saw your port and was excited to try it out.  Will keep a watch on it for later.  Thanks for your time!

**Comment by mikeew** [comment]
Having the same issue with SDL2_mixer, is it possible to switch it off (and sound) until a fix is available? With my setup it is not realistic to go back from RetroPie 4.3 to 3.8.
My setup:
rPI 3
RetroPie 4.3

Thanks for your work and looking forward to playing Bomberman!

**Comment by alexis-puska** [comment]
if you want to launch bomberman without audio, you can comment this 3 line in sound.cpp, just add // before this 3 line. 

if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, MIX_DEFAULT_CHANNELS, 1024) == -1) {
	printf("%s", Mix_GetError());
}

After that, compile and retry,

**Comment by mikeew** [comment]
Awesome, that worked a treat! Thank you!

Now that I have it running I have another question: how do I setup the input? At the moment I can only use the keyboard, the 2 wired and 2 wireless joypads/controllers do not work. All 4 joypads work in other games in retropie (ie. Bomberman for psx)

**Comment by alexis-puska** [comment]
In fact, i get the emulation station / retroarch gamepad configuration. 
The only setting you must made is on the screen that you set the type of player (CPU / HUMAN).
when you start a game, all the pad are active. be sure that the pad is connected before start the game.

you can start it in server mode, you can set after client join an third type of player (net) and you can define the start point of the player. 

PS : i glad you use the multitap on the psx emulator (pcsx rearmed i think), the multitap adaptation for this emulator it's a work that i made in 2016

**Comment by mikeew** [comment]
Good work on both lr-multi-bomberman and the multitap for the PSX emulator, it's brought us hours for fun!
You haven't written a multitap implementation for the Amiga/UAE version by any chance? :)

**Comment by alexis-puska** [comment]
On winUAE i d'ont remember to have a multitap on my amiga 500 (apydia, nebulus, hybris, shadow of the beast...) a great period.
I work on an other project when i have some free time, "In the well" a clone of hammerfest cavern (www.hammerfest.fr). The game dying and no response of the developer. I hope to finish this before mars 2018.

**Comment by alexis-puska** [comment]
I commit a fix, i think that work, i have reinstall the retropie 4.3 version but at this time i can't install SDL2-devel (repository down). if someone can update with the menu, compile and test ?

**Comment by mikeew** [comment]
I'll do it later on tonight and let you know :)

**Comment by alexis-puska** [comment]
I have change the repository and have test it, actually it's works on retropie 4.3 with raspbian Jessie version. i have test on ubuntu too and mac os X, and works.

To update and compile on you raspberry pi from the emulation station menu, you can execute in this order : 
UPDATE
COMPILE PI

and launch
BOMBERMAN

**Comment by alexis-puska** [comment]
@Rarefy-Dev 
Fix on retropie 4.3 (jessie), can you update, test and close the issues in this case ?
